# Generated by Django 3.2.8 on 2022-01-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('Necessary', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('full_content', models.TextField()),
            ],
        ),
    ]
