# Generated by Django 4.0.2 on 2022-02-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('Necessary', models.BooleanField(blank=True, default=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('full_content', models.TextField()),
                ('date', models.DateField(null=True)),
                ('hour', models.TimeField()),
                ('action', models.CharField(choices=[('برداشت', 'withdrawal'), ('واریز', 'deposit')], default='برداشت', max_length=50)),
                ('baghi', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
