# Generated by Django 3.2.8 on 2022-01-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
