# Generated by Django 3.2.8 on 2022-01-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arz', '0002_alter_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ساخت'),
        ),
    ]
