# Generated by Django 3.2.8 on 2022-01-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arz', '0003_transaction_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_on']},
        ),
    ]
